CI phpstan diff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,12 +19,10 @@ jobs:
         run: composer install
       - name: Run cs fixer
         run: composer run-script lint
-      - name: Run PHPStan baseline
-        run: vendor/bin/phpstan analyse --generate-baseline phpstan-baseline-ci.neon --allow-empty-baseline
-      - name: Compare PHPStan baseline with PR's baseline
+      - name: Check for phpstan-baseline.neon in PR
         run: |
-          if ! diff -u phpstan-baseline.neon phpstan-baseline-ci.neon; then
-            echo "Error: The generated phpstan-baseline.neon differs from the one provided in the PR.";
+          if ! git diff --name-only origin/main | grep -q 'phpstan-baseline.neon'; then
+            echo "Error: The phpstan-baseline.neon file is missing in the Pull Request.";
             exit 1;
           fi
 
