testlol1

diff --git a/.github/workflows/main-deployment.yml b/.github/workflows/main-deployment.yml
--- a/.github/workflows/main-deployment.yml
+++ b/.github/workflows/main-deployment.yml
@@ -23,9 +23,14 @@ jobs:
       - name: Extract Version from Commit Message
         id: extract_version
         run: |
-          echo "VERSION=1.20.1" >> $GITHUB_ENV
+          VERSION=$(git log -1 --pretty=%B | grep -oP '(release|hotfix)/\K[0-9]+\.[0-9]+(\.[0-9]+)?')
+          if [ -z "$VERSION" ]; then
+          echo "Version not found in commit message."
+          exit 1
+          fi
+          echo "VER=$VERSION" >> $GITHUB_ENV
 
       - name: Create Tag on Main
         run: |
-          git tag "v${VERSION}"
-          git push origin "v${VERSION}"
+          git tag "v${VER}"
+          git push origin "v${VER}"
